### ISSUE TITLE
Suggestion: set default sorting

### ISSUE THREAD

**Issue by Sabeurre** [Guerra24/LRReader#13]
Hi,
It would be nice if we could set a "default sorting", I like having my galleries always sorted by their gallery_id or date_added so that I get a similar experience to browsing exh. So far we have to redo the sorting each time we start LRR or a new search window is being opened.
This might seem like something minor but it's the only thing that prevents me from adopting LRR full time.
Anyway thanks for reading and paying attention to my request.

**Comment by Guerra24** [comment]
Hey! I've implemented default values for both *sort by* and *order by*, next release should be available later after testing. I'm going to close this once that is complete.

**Comment by Guerra24** [comment]
Release 1.5.2.0 is now out with those changes. Feel free to reopen if there are any issues.
