### ISSUE TITLE
Issue with the resizing algorithm

### ISSUE THREAD

**Issue by Sabeurre** [Guerra24/LRReader#14]
High resolution images viewed on LRR are not looking great.
here is an image (4200x6000) with Cdisplay using lanczos https://i.imgur.com/2x5F6V0.jpg
here the same image viewed with LRR https://i.imgur.com/307M4lI.jpg
It seems the algorithm used is not ideal with high resolution.
(It's also possible I'm just doing something wrong)

suggestion: 
- change the resizing algorithm for lanczos
- or add a option to let the user chose his preferred algorithm

As always, thanks for reading.

**Comment by Guerra24** [comment]
Fixed the image filtering and downscale, unfortunately I cannot set which algorithm is used but made some tests with 2400x3388 images and it looks fine. [Before](https://s3.guerra24.net/ShareX/2020/12/ApplicationFrameHost_2020-12-19_16-22-57.png) - [After](https://s3.guerra24.net/ShareX/2020/12/ApplicationFrameHost_2020-12-19_16-39-50.png)

Meanwhile I would suggest updating to nightly and then in January manually update to 1.5.4.0 (or whatever version is the latest) as I'm not planning to do doing a full release right now (unless something breaks). Just install it as any other update.

**Comment by Sabeurre** [comment]
Thanks still looks way better!

**Comment by Guerra24** [comment]
Release 1.5.4.0 is now out with those changes.
