### ISSUE TITLE
Ability to toggle turning pages with scrolling.

### ISSUE THREAD

**Issue by Radioo** [Guerra24/LRReader#17]
I'd love it if there was an option to disable scroll wheel page changing on the reader.
I often don't know if I'm on the bottom of the page so I scroll more and end up changing pages when I don't want to.

**Comment by Guerra24** [comment]
Hello. Added, I don't have an ETA for the full release but meanwhile you can use the nightly version.

![image](https://user-images.githubusercontent.com/9023392/127784180-84fb89b9-dd52-4153-a645-b84be186ea63.png)

**Comment by Guerra24** [comment]
Release 1.6.9 is now out with the new setting!
