### ISSUE TITLE
Delete function in bulk editor doesn't delete all archives.

### ISSUE THREAD

**Issue by omfgntsa** [Guerra24/LRReader#28]
Hi, I was deleting some archives and the tool doesn't delete all selected archives in one go, instead it seems to delete them in halves? Is this intended or was there a setting I missed.

Here is a short clip of what I'm talking about
https://imgur.com/vaBf1qR

**Comment by Guerra24** [comment]
Whoops, that should not happen. I'll take a look 👀

**Comment by Guerra24** [comment]
Fixed in the latest nightly.

**Comment by Guerra24** [comment]
v1.8.0 is now out with the fix!
