### ISSUE TITLE
Add de-duplication options in a context menu.

### ISSUE THREAD

**Issue by fuka-eri** [Guerra24/LRReader#35]
Attempting to de-duplicate when your library contains chapters of a larger book with very similar thumbnails (i.e. the same image with a different volume number) is currently a lot slower than it could be. Adding the option to mark a set as a duplicate or not from the main de-duplicator page without having to open the pair can help speed up the process when it is obvious they are not duplicates.

**Comment by Guerra24** [comment]
v1.8.2 is now out with this change!
