### ISSUE TITLE
Ability to sync duplicate exceptions between multiple computers

### ISSUE THREAD

**Issue by ChronoStriker1** [Guerra24/LRReader#37]
There may be a way to do this but I didn't see anything that jumped out at me.  I occasionally do a deduplication from two different computers.  Due to some Manga being released in chapters setting exceptions can be a large task.  Since I am doing it from two computers I have to do the same exceptions multiple times, when a series have 20 chapters released as volumes I'd like to only have to do this once (granted it would be nice to be able to group a series of volumes or chapters into a single entry, but that's more of a request for lanraragi itself then lrreader.)

**Comment by Guerra24** [comment]
Hello!

This used to be a thing when MS still hadn't _"Killed"_ UWP, but now... It's quite hard. I could take a hit at it and make my own account/settings/sync platform thing, but I don't really have the time. I have thought about it, tho.

As of right now, what you could do is go to the following paths and copy the entire profile json or only the field `MarkedAsNonDuplicated` for each profile which holds the exceptions.

For store
`C:\Users\<user>\AppData\Local\Packages\63705Guerra24.LRReader_pd6jswmanqqw0\LocalState`

For sideload
`C:\Users\<user>\AppData\Local\Packages\Guerra24.LRReader_3fr0p4qst6948\LocalState`

**Comment by ChronoStriker1** [comment]
That will work fine for me but a quick and dirty way that I think most people would be ok with is if we can manually set the path, that way in my situation I would sync it to a google drive location or even a network share that both computers have access to.

**Comment by Guerra24** [comment]
After checking some docs, this seems doable. I could let users pick a file path where the profile config would be stored. The main issue is retaining read/write access to it, but that appears to be covered already. I will take a look.

For reference so I don't forget: https://learn.microsoft.com/en-us/uwp/api/windows.storage.accesscache.storageitemaccesslist?view=winrt-22621

**Comment by Guerra24** [comment]
It should work with local drives, network drives, network paths and One Drive/Google Drive. You can try it on the nightly version. It might be missing an option to use an existing file, but we will see if it is really needed.

![image](https://github.com/Guerra24/LRReader/assets/9023392/27d24201-6309-4985-abf9-18b7ea1fdc8d)

**Comment by Guerra24** [comment]
v1.8.2 is now out with this change!
