### ISSUE TITLE
[Request] Added information to deduplication display

### ISSUE THREAD

**Issue by ChronoStriker1** [Guerra24/LRReader#41]
If possible can you add a section for the file path (possibly with file name) as well as archive file size to the deduplication display.  It will help when choosing which version of a file is the best one to keep when things like image size and other factors may be the same.  And as not to open another request, if possible can you make the tags lists scrollable?  When a file has a large number of tags or I should say if the namespace list is long enough it can cause images not to shown on smaller displays.

**Comment by Guerra24** [comment]
Hello!

The following information has been added to the latest nightly and will show up if you use LRR 0.9.10 (currently only on nightly too). File size appears to not be working right now, I already reported that, I will let you know here when that gets sorted out.
![image](https://github.com/Guerra24/LRReader/assets/9023392/c6b0df6f-9d87-4efa-a5b5-85a11f54b180)

**Comment by ChronoStriker1** [comment]
I can confirm I see what you have in the screenshot, filetype shows, but nothing for File Size or File Name.

**Comment by ChronoStriker1** [comment]
It just started showing file name and file size while I was going through some duplicates.

**Comment by Guerra24** [comment]
v1.8.2 is now out with this change!
