### ISSUE TITLE
Bookmarks not updating page count

### ISSUE THREAD

**Issue by krakerz** [Guerra24/LRReader#45]
is there a way to fix this ?

https://github.com/user-attachments/assets/85a856eb-4ac1-4c69-a91d-e6d3674d5dca

i already tried rescan archive on server side, clear cache on the app, it still has this issue, and i can't get past of page 55, i can go jump via thumbnails, but can't progress from it

![image](https://github.com/user-attachments/assets/82a1190c-6d8f-4540-9e9c-4bba7bc744e4)

step to reproduce, i think if you updated the archive with more files inside the zip files, and rescan it (on web it was fine), for example first file is 55 pages, then you update it into 381 pages like me, and just do the rescan in server, it will retain the metadata (helpful for me to finish 1 archive / book that still uncompleted)
![image](https://github.com/user-attachments/assets/ba8a07b9-3ab9-4839-b3bf-ac41f2e7aac0)

**Comment by Guerra24** [comment]
Hello!

Unbookmark and bookmark it again. This is legacy behavior from when the API didn't return the page count and instead was saved in the bookmark metadata. Fixed this locally.

**Comment by krakerz** [comment]
> Hello!
> 
> Unbookmark and bookmark it again. This is legacy behavior from when the API didn't return the page count and instead was saved in the bookmark metadata. Fixed it locally.

ah yes, thank you, it's solved on my end, what i did was
unbookmark > refresh once (to make sure) > bookmark it again, it's properly save the page count

thank you very much, btw out of topic, what API did you use / method to go next archieve? since i want to propose this function to ichaival for android and lanreader for ios if possible, it's one of the best feature in LRR for me

**Comment by Guerra24** [comment]
> what API did you use / method to go next archieve?

There are no APIs for this, it uses the results from the search tab they were opened from.

**Comment by krakerz** [comment]
> > what API did you use / method to go next archieve?
> 
> There are no APIs for this, it uses the results from the search tab they were opened from.

ah i see, RIP then, since they asked an API for it, i'll close this issue since i found the solution, thank you
